import google.generativeai as genai
import os
from dotenv import load_dotenv
from src.agent.tools import execute_graphql_query, generar_pdf_tool, generar_excel_tool

load_dotenv()  # Load environment variables from .env file

# Configure the API key
# Make sure to set the GOOGLE_API_KEY environment variable
api_key = os.getenv("GOOGLE_API_KEY")
if not api_key:
    raise ValueError("GOOGLE_API_KEY environment variable not set.")

genai.configure(api_key=api_key)

# Define the tools that the agent can use.
# We provide the function directly to the model.
tools = [execute_graphql_query, generar_pdf_tool, generar_excel_tool]

# Create the generative model with the defined tools
model = genai.GenerativeModel(model_name="gemini-2.5-flash", tools=tools)


def run_agent(prompt: str) -> dict:
    """
    Runs the agent with a given prompt.

    Args:
        prompt (str): The user's request in natural language.

    Returns:
        dict: A structured response. Can be:
        - `{"type": "text", "content": "..."}` for a text response.
        - `{"type": "report", "format": "pdf|excel", "path": "reports/file.pdf"}` for a report.
    """
    print(f"User prompt: {prompt}")

    # Start a chat session
    chat = model.start_chat(enable_automatic_function_calling=True)

    # Send the prompt to the model
    response = chat.send_message(prompt)

    # The model will automatically call the necessary functions.
    # The response will contain the final result after the function calls.

    # We just need to get the text part of the final response.
    final_response = ""
    for chunk in response:
        if chunk.text:
            final_response += chunk.text

    # Check if a report was generated by looking for the log messages
    # This is a simple check. A more robust implementation would parse the function call results.
    if "PDF report generated:" in final_response:
        # Extract the file path from the log message
        # This is a very naive way to do it. In a real scenario, you would parse the function call result.
        parts = final_response.split("PDF report generated: ")
        if len(parts) > 1:
            file_path = parts[1].split("\n")[0].strip()
            return {"type": "report", "format": "pdf", "path": file_path}
    elif "Excel report generated:" in final_response:
        # Extract the file path from the log message
        parts = final_response.split("Excel report generated: ")
        if len(parts) > 1:
            file_path = parts[1].split("\n")[0].strip()
            return {"type": "report", "format": "excel", "path": file_path}

    # If no report was generated, return the text response
    return {"type": "text", "content": final_response}


if __name__ == "__main__":
    # Example of how to run the agent
    # This prompt should trigger the agent to use the GraphQL tool
    user_request = "Quiero un listado de todas las especialidades médicas disponibles."
    run_agent(user_request)
